# For more info on HTTP files go to https://aka.ms/vs/httpfile
@Api_HostAddress = https://localhost:7051

POST {{Api_HostAddress}}/CreateCustomer
Content-Type: application/json

{
    "Firstname": "John",
    "Surname": "Shephard",
    "Email": "jshephard@alliance.mil",
    "Address": {
        "AddressLine1": "1 Citadel Promenade",
        "AddressLine2": "Bromley",
        "AddressLine3": "",
        "County": "Kent",
        "Country": "England",
        "PostalCode": "BR1 9QW"
    }
}
###

POST {{Api_HostAddress}}/CreateCustomer
Content-Type: application/json

{
    "Firstname": "Tali",
    "Surname": "Vas Normandy",
    "Email": "tvNormandy@alliance.mil",
    "Address": {
        "AddressLine1": "1 Citadel Promenade",
        "AddressLine2": "Bromley",
        "AddressLine3": "",
        "County": "Croydon",
        "Country": "England",
        "PostalCode": "CR1 9QW"
    }
}
###

POST {{Api_HostAddress}}/CreateCustomer
Content-Type: application/json

{
    "Firstname": "Urdnot",
    "Surname": "Wrex",
    "Email": "uWrex@alliance.mil",
    "Address": {
        "AddressLine1": "1 Citadel Promenade",
        "AddressLine2": "Tuchaka",
        "AddressLine3": "",
        "County": "Cornwall",
        "Country": "England",
        "PostalCode": "TU1 9QW"
    }
}
###

GET {{Api_HostAddress}}/GetCustomers
###

GET {{Api_HostAddress}}/GetDeliveryCheck/3
###